#!/bin/bash

# WCC: The Word Compiler Collection
# Compile Word documents as C code 

## Flag Vars
OUTFILE="a.out"
COMPILE_ONLY=""
WARN_NAMES="" # list of warning names, i.e. "all error"
STD_C="" # C standard to use, i.e. c99

while getopts W:co:s:h o
do
    case "$o" in
    W)  echo "Found option $OPTARG"
        WARN_NAMES+="$OPTARG ";;
    c) COMPILE_ONLY="-c";;
    o) OUTFILE="$OPTARG";;
    s) STD_C="-s$OPTARG";;
    h) printf >&2 "
WCC: The Word Compiler Collection
Usage: wcc [options] FILE
-W warn     Set warnings, i.e. all, error
-c          Compile, but do not link
-o out      Specify output file name
-std=std    Set C standard to use, i.e. c99
-h          Show this help
" && exit 0;;
    [?]) printf >&2 "Unknown flag $OPTARG" && exit 0;;
    esac
done
shift $(($OPTIND-1))


## Functions
get_warnings_for_warn_names() {
    local WARN_NAMES=$@
    local result=""
    # iteration requires `setopt shwordsplit` for ZSH
    for name in $WARN_NAMES
    do
        result+="-W$name "
    done 
    echo $result
}


## Vars
INFILE="$@"
BASENAME="$(basename $INFILE)"
WARNINGS="$(get_warnings_for_warn_names $WARN_NAMES)"


### Extract code from Word XML
unzip -p "$INFILE" word/document.xml | \
    sed -e 's/<\/w:p>/你/g; s/<w:br\/>/你/g; s/<\/w:pPr>/你/g; s/<w:tab\/>/空/g; s/<[^>]\{1,\}>//g; s/[^[:print:]\n]\{1,\}//g; s/&lt;/</g; s/&gt;/>/g; ' | \
    sed -e 's/“/"/g; s/”/"/g' | \
    tr '你' '\n' | \
    tr '空' '\t' > "temp.$BASENAME.c"


### Compile code 
gcc $WARNINGS "$COMPILE_ONLY" "temp.$BASENAME.c" -o "$OUTFILE"